### ISSUE TITLE
Provide a way to record "earns".

### ISSUE THREAD

**Issue by ryasmi** [ht2/BadgesCoP#2]
**Motive**
"earners" want to "earn" badges, so that they can "display" them outside of a backpack.

**Result**
Define the best practice for recording "earns".

**Comment by ryasmi** [comment]
### Endpoint

[POST http://www.example.com/xapi/statements](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#722-poststatements)

### Request body for recording a badge with a hosted assertion

``` json
{
  "verb": {"id": "http://standard.openbadges.org/xapi/verbs/earned.json"},
  "object": {
    "id": "www.example.com/badgeclass/1", 
    "definition": {
       "type": "http://activitystrea.ms/schema/1.0/badge"
    }
  },
  "result": {
    "extensions": {
      "http://standard.openbadges.org/xapi/extensions/badgeassertion.json": {
        "@id": "http://example.org/assertion/1"
      }
    }
  },
  "context": {
      "contextActivities": {
        "category": [
          {
            "id": "http://standard.openbadges.org/xapi/recipe/base/0",
            "definition": {
              "type": "http://id.tincanapi.com/activitytype/recipe"
            },
            "objectType": "Activity"
          }
        ]
     }
  }
}
```

### Request body for recording a badge with a signed assertion

``` json
{
  "verb": {"id": "http://standard.openbadges.org/xapi/verbs/earned.json"},
  "object": {
    "id": "www.example.com/badgeclass/1", 
    "definition": {
       "type": "http://activitystrea.ms/schema/1.0/badge"
    }
  },
  "result": {
    "extensions": {
     "http://standard.openbadges.org/xapi/extensions/signedbadgeassertion.json": "eyJhbGciOiJSUzI1NiJ9.eyJ1aWQiOiJhYmMtMTIzNCIsInJlY2lwaWVudCI6eyJ0eXBlIjoiZW1haWwiLCJoYXNoZWQiOnRydWUsInNhbHQiOiJkZWFkc2VhIiwiaWQiOiJzaGEyNTYkYzdlZjg2NDA1YmE3MWI4NWFjZDhlMmU5NTE2NmM0YjExMTQ0ODA4OWYyZTE1OTlmNDJmZTFiYmE0NmU4NjVjNSJ9LCJpbWFnZSI6Imh0dHBzOi8vZXhhbXBsZS5vcmcvYmV0aHMtcm9ib3QtYmFkZ2UucG5nIiwiZXZpZGVuY2UiOiJodHRwczovL2V4YW1wbGUub3JnL2JldGhzLXJvYm90LXdvcmsuaHRtbCIsImlzc3VlZE9uIjoxMzU5MjE3OTEwLCJiYWRnZSI6Imh0dHBzOi8vZXhhbXBsZS5vcmcvcm9ib3RpY3MtYmFkZ2UuanNvbiIsInZlcmlmeSI6eyJ0eXBlIjoic2lnbmVkIiwidXJsIjoiaHR0cHM6Ly9leGFtcGxlLm9yZy9wdWJsaWNLZXkucGVtIn19.Liv4CLviFH20_6RciUWf-jrUvMAecxT4KZ_gLHAeT_chrsCvBEE1uwgtwiarIs9acFfMi0FJzrGye6mhdHf3Kjv_6P7BsG3RPkYgK6-5i9uZv4QAIlvfNclWAoWUt4j0_Kip2ftzzWwc5old01nJRtudZHxo5eGosSPlztGRE9G_g_cTj32tz3fG92E2azPmbt7026G91rq80Mi-9c4bZm2EgrcwNBjO0p1mbKYXLIAAkOMuJZ_8S4Go8S0Sg3xC6ZCn03zWuXCP6bdY_jJx2BpmvqC3H55xWIU8p5c9RxI8YifPMmJq8ZQhjld0pl-L8kHolJx7KGfTjQSegANUPg"
    }
  },
  "context": {
      "contextActivities": {
        "category": [
          {
            "id": "http://standard.openbadges.org/xapi/recipe/base/0",
            "definition": {
              "type": "http://id.tincanapi.com/activitytype/recipe"
            },
            "objectType": "Activity"
          }
        ]
     }
  }
}
```

**Comment by garemoko** [comment]
On gitter we discussed using all lower case for the identifiers.

**Comment by ryasmi** [comment]
You're absolutely right, this was just copied and pasted from a message I'd
sent. I intend to edit it tomorrow. I did start editing it, then some other
things came up, then I had to leave for my train so I just submitted the
comment as it was before I left :-)

**Comment by ottonomy** [comment]
https://github.com/openbadges/openbadges-specification/pull/22  -- Here's a pull request containing the proposed necessary documents to be posted with the OBI specification. Would love some comment on them. I bet they will need revision of some kind, just don't have enough experience with xAPI to know what.

**Comment by ryasmi** [comment]
I've updated the examples above, let me know if anything is wrong with them.

**Comment by garemoko** [comment]
Looks right to me. I also added some comments at https://github.com/openbadges/openbadges-specification/pull/22. Obviously it's important that we match up, and I wonder if the Open Badges wiki/documentation should be the source of truth that we replicate or even simply reference here. 

In that case, Ryan would PR this into https://github.com/ottonomy/openbadges-specification/tree/xapi I guess?

**Comment by ottonomy** [comment]
Yep, @garemoko, it would be great to have a couple implementation examples in the badges docs. PR them to that branch. Next Tuesday, we'll discuss this at the badges specification working group meeting. 10:30am Pacific, and I can get anybody who's interested the link to the call around the beginning of next week.

**Comment by ryasmi** [comment]
I think since the discussions would be taking place here I think it's best to keep this repository as the source of truth (SoT to keep it all together and reference the OB spec where necessary. If the OB wiki is the SoT then people may not know to report issues here.

**Comment by ryasmi** [comment]
I'm happy for the verb definitions (etc) to live there since they should be immutable.

**Comment by garemoko** [comment]
That context isn't right. it needs to be within the extensions property.

**Comment by ryasmi** [comment]
Good spot. Updated :+1:

**Comment by ryasmi** [comment]
Updated with @garemoko's latest work.
